FROM ruby:2.3.0

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      build-essential \
      memcached \
      vim \
      less

RUN apt-get clean \
 && apt-get autoremove -y \
 && apt-get moo
